# This is the dict that is returned by WorkflowDefinitionConfigurator.getWorkflowInfo(),
# in this case for plone_workflow.

{'description': " - Users can create content that is immediately publicly accessible. - Content can be submitted for publication by the content's creator or a Manager, which is typically done to promote events or news to the front page. - Reviewers can publish or reject content, content owners can retract their submissions. - While the content is awaiting review it is readable by anybody. - If content is published, it can only be retracted by a Manager.",
 'id': 'plone_workflow',
 'initial_state': 'visible',
 'meta_type': 'Workflow',
 'permissions': ('Access contents information',
                 'Change portal events',
                 'Modify portal content',
                 'View'),
 'script_info': [],
 'state_info': [{'description': 'Waiting to be reviewed, not editable by the owner.\n',
                 'groups': [],
                 'id': 'pending',
                 'permissions': [{'acquired': False,
                                  'name': 'Access contents information',
                                  'roles': ('Anonymous',)},
                                 {'acquired': False,
                                  'name': 'Change portal events',
                                  'roles': ('Manager', 'Reviewer')},
                                 {'acquired': False,
                                  'name': 'Modify portal content',
                                  'roles': ('Manager', 'Reviewer')},
                                 {'acquired': False,
                                  'name': 'View',
                                  'roles': ('Anonymous',)}],
                 'title': 'Pending review',
                 'transitions': ('hide', 'publish', 'reject', 'retract'),
                 'variables': []},
                {'description': 'Can only be seen and edited by the owner.\n',
                 'groups': [],
                 'id': 'private',
                 'permissions': [{'acquired': False,
                                  'name': 'Access contents information',
                                  'roles': ('Manager',
                                            'Owner',
                                            'Reader',
                                            'Editor',
                                            'Contributor')},
                                 {'acquired': False,
                                  'name': 'Change portal events',
                                  'roles': ('Manager', 'Owner', 'Editor')},
                                 {'acquired': False,
                                  'name': 'Modify portal content',
                                  'roles': ('Manager', 'Owner', 'Editor')},
                                 {'acquired': False,
                                  'name': 'View',
                                  'roles': ('Manager',
                                            'Owner',
                                            'Reader',
                                            'Editor',
                                            'Contributor')}],
                 'title': 'Private',
                 'transitions': ('show',),
                 'variables': []},
                {'description': 'Visible to everyone, not editable by the owner.\n',
                 'groups': [],
                 'id': 'published',
                 'permissions': [{'acquired': False,
                                  'name': 'Access contents information',
                                  'roles': ('Anonymous',)},
                                 {'acquired': False,
                                  'name': 'Change portal events',
                                  'roles': ('Manager',)},
                                 {'acquired': False,
                                  'name': 'Modify portal content',
                                  'roles': ('Manager',)},
                                 {'acquired': False,
                                  'name': 'View',
                                  'roles': ('Anonymous',)}],
                 'title': 'Published',
                 'transitions': ('reject', 'retract'),
                 'variables': []},
                {'description': 'Visible to everyone, but not approved by the reviewers.\n',
                 'groups': [],
                 'id': 'visible',
                 'permissions': [{'acquired': False,
                                  'name': 'Access contents information',
                                  'roles': ('Anonymous',)},
                                 {'acquired': False,
                                  'name': 'Change portal events',
                                  'roles': ('Manager', 'Owner', 'Editor')},
                                 {'acquired': False,
                                  'name': 'Modify portal content',
                                  'roles': ('Manager', 'Owner', 'Editor')},
                                 {'acquired': False,
                                  'name': 'View',
                                  'roles': ('Anonymous',)}],
                 'title': 'Public draft',
                 'transitions': ('hide', 'publish', 'submit'),
                 'variables': []}],
 'state_variable': 'review_state',
 'title': 'Community Workflow',
 'transition_info': [{'actbox_category': 'workflow',
                      'actbox_name': 'Make private',
                      'actbox_url': '%(content_url)s/content_status_modify?workflow_action=hide',
                      'after_script_name': '',
                      'description': 'Making an item private means that it will not be visible to anyone but the owner and the site administrator.\n',
                      'guard_expr': '',
                      'guard_groups': (),
                      'guard_permissions': ('Modify portal content',),
                      'guard_roles': (),
                      'id': 'hide',
                      'new_state_id': 'private',
                      'script_name': '',
                      'title': 'Member makes content private',
                      'trigger_type': 'USER',
                      'variables': []},
                     {'actbox_category': 'workflow',
                      'actbox_name': 'Publish',
                      'actbox_url': '%(content_url)s/content_status_modify?workflow_action=publish',
                      'after_script_name': '',
                      'description': 'Publishing the item makes it visible to other users.\n',
                      'guard_expr': '',
                      'guard_groups': (),
                      'guard_permissions': ('Review portal content',),
                      'guard_roles': (),
                      'id': 'publish',
                      'new_state_id': 'published',
                      'script_name': '',
                      'title': 'Reviewer publishes content',
                      'trigger_type': 'USER',
                      'variables': []},
                     {'actbox_category': 'workflow',
                      'actbox_name': 'Send back',
                      'actbox_url': '%(content_url)s/content_status_modify?workflow_action=reject',
                      'after_script_name': '',
                      'description': 'Sending the item back will return the item to the original author instead of publishing it. You should preferably include a reason for why it was not published.\n',
                      'guard_expr': '',
                      'guard_groups': (),
                      'guard_permissions': ('Review portal content',),
                      'guard_roles': (),
                      'id': 'reject',
                      'new_state_id': 'visible',
                      'script_name': '',
                      'title': 'Reviewer sends content back for re-drafting',
                      'trigger_type': 'USER',
                      'variables': []},
                     {'actbox_category': 'workflow',
                      'actbox_name': 'Retract',
                      'actbox_url': '%(content_url)s/content_status_modify?workflow_action=retract',
                      'after_script_name': '',
                      'description': 'If you submitted the item by mistake or want to perform additional edits, this will take it back.\n',
                      'guard_expr': '',
                      'guard_groups': (),
                      'guard_permissions': ('Request review',),
                      'guard_roles': (),
                      'id': 'retract',
                      'new_state_id': 'visible',
                      'script_name': '',
                      'title': 'Member retracts submission',
                      'trigger_type': 'USER',
                      'variables': []},
                     {'actbox_category': 'workflow',
                      'actbox_name': 'Promote to Draft',
                      'actbox_url': '%(content_url)s/content_status_modify?workflow_action=show',
                      'after_script_name': '',
                      'description': 'Promotes your private item to a public draft.\n',
                      'guard_expr': '',
                      'guard_groups': (),
                      'guard_permissions': ('Modify portal content',),
                      'guard_roles': (),
                      'id': 'show',
                      'new_state_id': 'visible',
                      'script_name': '',
                      'title': 'Member promotes content to public draft',
                      'trigger_type': 'USER',
                      'variables': []},
                     {'actbox_category': 'workflow',
                      'actbox_name': 'Submit for publication',
                      'actbox_url': '%(content_url)s/content_status_modify?workflow_action=submit',
                      'after_script_name': '',
                      'description': 'Puts your item in a review queue, so it can be published on the site.\n',
                      'guard_expr': '',
                      'guard_groups': (),
                      'guard_permissions': ('Request review',),
                      'guard_roles': (),
                      'id': 'submit',
                      'new_state_id': 'pending',
                      'script_name': '',
                      'title': 'Member submits content for publication',
                      'trigger_type': 'USER',
                      'variables': []}],
 'variable_info': [{'default_expr': 'transition/getId|nothing',
                    'default_type': 'string',
                    'default_value': '',
                    'description': 'Previous transition\n',
                    'for_catalog': False,
                    'for_status': True,
                    'guard_expr': '',
                    'guard_groups': (),
                    'guard_permissions': (),
                    'guard_roles': (),
                    'id': 'action',
                    'update_always': True},
                   {'default_expr': 'user/getId',
                    'default_type': 'string',
                    'default_value': '',
                    'description': 'The ID of the user who performed the last transition\n',
                    'for_catalog': False,
                    'for_status': True,
                    'guard_expr': '',
                    'guard_groups': (),
                    'guard_permissions': (),
                    'guard_roles': (),
                    'id': 'actor',
                    'update_always': True},
                   {'default_expr': "python:state_change.kwargs.get('comment', '')",
                    'default_type': 'string',
                    'default_value': '',
                    'description': 'Comment about the last transition\n',
                    'for_catalog': False,
                    'for_status': True,
                    'guard_expr': '',
                    'guard_groups': (),
                    'guard_permissions': (),
                    'guard_roles': (),
                    'id': 'comments',
                    'update_always': True},
                   {'default_expr': 'state_change/getHistory',
                    'default_type': 'string',
                    'default_value': '',
                    'description': 'Provides access to workflow history\n',
                    'for_catalog': False,
                    'for_status': False,
                    'guard_expr': '',
                    'guard_groups': (),
                    'guard_permissions': ('Request review',
                                          'Review portal content'),
                    'guard_roles': (),
                    'id': 'review_history',
                    'update_always': False},
                   {'default_expr': 'state_change/getDateTime',
                    'default_type': 'string',
                    'default_value': '',
                    'description': 'When the previous transition was performed\n',
                    'for_catalog': False,
                    'for_status': True,
                    'guard_expr': '',
                    'guard_groups': (),
                    'guard_permissions': (),
                    'guard_roles': (),
                    'id': 'time',
                    'update_always': True}],
 'worklist_info': [{'actbox_category': 'global',
                    'actbox_name': 'Pending (%(count)d)',
                    'actbox_url': '%(portal_url)s/search?review_state=pending',
                    'description': 'Reviewer tasks\n',
                    'guard_expr': '',
                    'guard_groups': (),
                    'guard_permissions': ('Review portal content',),
                    'guard_roles': (),
                    'id': 'reviewer_queue',
                    'title': '',
                    'var_match': [('review_state', 'pending')]}]}
